Refactoring
LBHackney-IT/lbh-adult-social-care-frontend pull request #114
Opened 2021-09-13 14:41 UTC by mugnivenko

2021-09-14 15:34 UTC, akeamwoodsND reviewed
on going selection no longer works? (on http://localhost:3000/care-package)
<img width="389" alt="Screenshot 2021-09-14 at 16 34 24" src="https://user-images.githubusercontent.com/89010589/133288276-fccb9bf7-27d8-447a-aa3a-56ed5a5959da.png">

2021-09-14 15:34 UTC, akeamwoodsND commented on components/PayRuns/PayRunsHeader.js
> +import { checkEmptyFields } from '../../service/formValidator'
service/formValidator

2021-09-15 08:19 UTC, mugnivenko commented
ongoing date picker fixed

2021-09-15 09:00 UTC, akeamwoodsND requested changes
Delete <div id='modal' /> from pages/index.js

2021-09-15 11:21 UTC, merged