Concept/date picker
LBHackney-IT/lbh-adult-social-care-frontend pull request #123
Opened 2021-09-21 11:13 UTC by mugnivenko

2021-09-21 11:31 UTC, akeamwoodsND requested changes
<img width="922" alt="Screenshot 2021-09-21 at 12 27 35" src="https://user-images.githubusercontent.com/89010589/134163116-d203b39e-f706-46b4-98bc-8cd3cd0bdebb.png">

Alignment issues

2021-09-28 08:59 UTC, akeamwoodsND requested changes

2021-09-28 08:59 UTC, akeamwoodsND commented on components/HackneyDS/FormGroup/index.js
> +        <legend className="govuk-fieldset__legend">{label}</legend>
- This change affects the RadioGroup storybook (rename prop in storybook to label).
- Change <legend> to <Label> component

2021-09-28 09:06 UTC, akeamwoodsND requested changes
Each section should be two digits long (e.g. 2/2/12 -> 02/02/12)
<img width="317" alt="Screenshot 2021-09-28 at 10 05 32" src="https://user-images.githubusercontent.com/89010589/135057868-f4e25bc3-3cf4-403a-a1f3-84963790740b.png">

2021-09-28 11:15 UTC, mugnivenko commented
(Fixed) Each section should be two digits long (e.g. 2/2/12 -> 02/02/12)

2021-09-28 12:20 UTC, akeamwoodsND requested changes
Label prop missing on radio group storybook examples
<img width="560" alt="Screenshot 2021-09-28 at 13 19 35" src="https://user-images.githubusercontent.com/89010589/135085428-c1ddf2bc-8f27-4b88-8fa9-1da5a30d103b.png">

2021-09-28 12:45 UTC, mugnivenko commented
(Done) Change prop (title) to (label)

2021-09-28 13:06 UTC, akeamwoodsND requested changes
`cursor: pointer;` over calendar icon

2021-09-28 13:09 UTC, akeamwoodsND requested changes
Label is wrong on date picker, look at difference between date picker label and input label
<img width="496" alt="Screenshot 2021-09-28 at 14 04 52" src="https://user-images.githubusercontent.com/89010589/135092723-826cc88d-b0d5-4ff5-83da-2d087294c17d.png">
<img width="751" alt="Screenshot 2021-09-28 at 14 05 05" src="https://user-images.githubusercontent.com/89010589/135092731-3d507683-9f5a-417d-acb9-23a0f13f7be5.png">

2021-09-28 15:48 UTC, akeamwoodsND requested changes
Why are there two sets of labels and hints?
<img width="514" alt="Screenshot 2021-09-28 at 16 47 27" src="https://user-images.githubusercontent.com/89010589/135121281-0993dc8a-9bb4-4413-84af-5fdd195d9cc7.png">

2021-09-29 08:15 UTC, merged