fix hide condition for details action buttons
LBHackney-IT/lbh-adult-social-care-frontend pull request #267
Opened 2021-11-02 11:25 UTC by mugnivenko

2021-11-02 13:55 UTC, mugnivenko commented
https://app.clickup.com/t/1phm2qm

2021-11-03 10:17 UTC, mugnivenko commented
https://app.clickup.com/t/1q2xk7k

2021-11-03 10:28 UTC, akeamwoodsND requested changes
This breaks changes I added. Go to this url on your branch and then on develop: http://localhost:3000/care-package/824186e9-4d72-490e-81ea-39780cb880c3/details 
This package has been ended so you shouldn't be able to see the cancel, end, edit buttons. On develop this is fine, on your branch I can see them
<img width="586" alt="Screenshot 2021-11-03 at 10 29 37" src="https://user-images.githubusercontent.com/89010589/140044825-28928b3a-6c21-4a69-a04f-3e35d7b41dca.png">
Why have you removed this logic? This is what has broken it.

2021-11-03 11:34 UTC, mugnivenko commented
i change condition for buttons in details page (status < 6)

2021-11-03 11:42 UTC, mugnivenko commented on pages/care-package/[guid]/details.js
> +      buttons={data?.status < 6 && [
i used your condition

2021-11-08 10:43 UTC, akeamwoodsND requested changes
edit/remove buttons still appear for cancelled/ended package e.g. care-package/e8c5f10f-c791-4cd3-8eaa-14fd1616ca60/details

2021-11-08 13:05 UTC, mugnivenko commented
> edit/remove buttons still appear for cancelled/ended package e.g. care-package/e8c5f10f-c791-4cd3-8eaa-14fd1616ca60/details
> 
> The buttons are also in the wrong position

I add condition for (edit, remove) buttons.
I coordinated the change of position with Burak, it's ok.

2021-11-09 11:37 UTC, akeamwoodsND requested changes
Do we want there to be a 'remove' button if there is nothing there to remove?
<img width="834" alt="Screenshot 2021-11-09 at 11 35 49" src="https://user-images.githubusercontent.com/89010589/140917275-50687ed0-7308-4b89-becd-fe68d689a2bd.png">

2021-11-10 09:03 UTC, mugnivenko commented
As Burak said to me, i need to merge two link into one link that says "Edit or Remove" with blue style

2021-11-10 09:03 UTC, mugnivenko commented on components/Pages/CarePackages/ReviewPackageDetails/PackageInfo.js
> +              Edit or Remove
![image](https://user-images.githubusercontent.com/77606518/141082857-2a076f7f-ebc1-4e32-8a90-6dbed215392e.png)

2021-11-10 10:03 UTC, akeamwoodsND requested changes
You shouldn't be able to edit an approved package e.g. /care-package/471fb9cc-6573-4f72-a90d-21bb7641ef5a/details
<img width="579" alt="Screenshot 2021-11-10 at 10 02 37" src="https://user-images.githubusercontent.com/89010589/141092628-5c14e3ac-b231-452d-a4c6-cd0365ba9a43.png">

2021-11-10 10:12 UTC, mugnivenko commented
> You shouldn't be able to edit an approved package e.g. /care-package/471fb9cc-6573-4f72-a90d-21bb7641ef5a/details <img alt="Screenshot 2021-11-10 at 10 02 37" width="579" src="https://user-images.githubusercontent.com/89010589/141092628-5c14e3ac-b231-452d-a4c6-cd0365ba9a43.png">

hide this button if status === 4 (Approved)

2021-11-10 11:08 UTC, akeamwoodsND approved these changes

2021-11-10 11:16 UTC, merged