Fix/create draft payrun inputs
LBHackney-IT/lbh-adult-social-care-frontend pull request #295
Opened 2021-11-11 06:17 UTC by mugnivenko

2021-11-11 14:09 UTC, akeamwoodsND commented on components/Pages/Finance/CreateDraftPayRun/CreatePayRunInfo.js
> +const CreatePayRunInfo = ({
Break this up into two components
<img width="615" alt="Screenshot 2021-11-11 at 14 06 33" src="https://user-images.githubusercontent.com/89010589/141311777-c6f739d2-595b-4caf-8a3c-d117c9261e4c.png">
and
<img width="629" alt="Screenshot 2021-11-11 at 14 06 58" src="https://user-images.githubusercontent.com/89010589/141311809-75c09681-fdc1-4535-80a1-6fed74fb88be.png">
It is better to have two simpler components than one complicated one with lots of props. I'd expect this component to look something like

```
<Modal>
<RegularCycles/>
<AdHocAndReleased/>
<Container>
<Button>Cancel</Button>
<Button>Create draft pay run</Button>
</Container>
</Modal>
```

2021-11-11 14:10 UTC, akeamwoodsND requested changes
See comment

2021-11-12 08:13 UTC, mugnivenko commented
Not full tested yet

2021-11-13 18:02 UTC, akeamwoodsND requested changes

2021-11-13 18:02 UTC, akeamwoodsND commented on components/Pages/Finance/CreateDraftPayRun/CreatePayRunInfo.js
> +const CreatePayRunInfo = ({
Having this component makes the code way more complicated, strip the logic into the other two files.

2021-11-15 09:30 UTC, akeamwoodsND requested changes

2021-11-15 09:30 UTC, akeamwoodsND commented on components/Pages/Finance/CreateDraftPayRun/CreatePayRunInfo.js
> +import { Controller } from 'react-hook-form';
Delete this component

2021-11-15 10:43 UTC, akeamwoodsND requested changes
Also please revert the changes on the tabs, just use the default tabs without style changes. I know the figma design has it how you have made it, but that is **not** following the HDS which we should be doing
<img width="657" alt="Screenshot 2021-11-15 at 10 42 32" src="https://user-images.githubusercontent.com/89010589/141768071-28c243ac-9d75-466d-b54d-1008a7e35107.png">

2021-11-15 10:46 UTC, akeamwoodsND requested changes
<img width="595" alt="Screenshot 2021-11-15 at 10 43 56" src="https://user-images.githubusercontent.com/89010589/141768163-6f79698e-da4c-4c8a-91ce-7c199f2ab79c.png">
<img width="633" alt="Screenshot 2021-11-15 at 10 44 12" src="https://user-images.githubusercontent.com/89010589/141768197-5ab81dcd-706d-4795-8cbc-4a970cbb0527.png">
Let's put better validation messages.

2021-11-15 10:46 UTC, akeamwoodsND requested changes
edit: ignore

2021-11-15 11:25 UTC, merged