Feature/invoice detail page
LBHackney-IT/lbh-adult-social-care-frontend pull request #314
Opened 2021-11-16 08:54 UTC by mugnivenko

https://app.clickup.com/t/1t1wu83

2021-11-16 12:58 UTC, akeamwoodsND requested changes

2021-11-16 13:00 UTC, mugnivenko commented on api/SWR/payRuns.js
> +const getPayRunUrl = (payRunId, additionalString = '') => getUrlOrNull(`${PAY_RUNS_URL}/${payRunId}${additionalString}`);
when it includes undefined string

2021-11-16 13:52 UTC, mugnivenko commented on api/SWR/payRuns.js
> +const getPayRunUrl = (payRunId, additionalString = '') => getUrlOrNull(`${PAY_RUNS_URL}/${payRunId}${additionalString}`);
we always write id !== undefined ? url : null. So i decided to create a function for that case

2021-11-16 14:18 UTC, mugnivenko commented on api/SWR/payRuns.js
> +  useGetData(getPayRunUrl(payRunId, `/invoices/${invoiceId}`))
if so, we 100% need to change all the url that depends on payrun

2021-11-16 14:51 UTC, akeamwoodsND requested changes

2021-11-16 14:51 UTC, akeamwoodsND commented on pages/payruns/[guid]/invoice/[id].js
> +        <h3 className="invoice-detail--title">Pay run period</h3>
use Heading component

2021-11-16 14:51 UTC, akeamwoodsND commented on pages/payruns/[guid]/invoice/[id].js
> +          className="invoice-detail--sub-title">{getEnGBFormattedDate(dateFrom)}{dateTo ? ` - ${getEnGBFormattedDate(dateTo)}` : ''}</p>
use Hint component

2021-11-17 09:01 UTC, akeamwoodsND requested changes

2021-11-17 09:01 UTC, akeamwoodsND commented on styles/css/Finance/invoice-detail.scss
> +.invoice-detail--title {
delete

2021-11-17 09:01 UTC, akeamwoodsND commented on pages/payruns/[guid]/invoice/[id].js
> +        <HintDate dateFrom={invoice.startDate} dateTo={invoice.endDate} />
delete this component, use normal Hint component

2021-11-17 09:01 UTC, akeamwoodsND commented on pages/payruns/[guid]/invoice/[id].js
> +        <Heading fontWeight={400} size='xl'>Pay run period</Heading>
remove font weight

2021-11-17 09:01 UTC, akeamwoodsND commented on pages/payruns/[guid]/invoice/[id].js
> +        <Heading fontWeight={400} size='xl'>Pay run period</Heading>
we want the headings on pages to look the same

2021-11-17 10:05 UTC, akeamwoodsND requested changes
breadcrumbs link is wrong, there's a console warning about it
<img width="1440" alt="Screenshot 2021-11-17 at 10 04 35" src="https://user-images.githubusercontent.com/89010589/142179971-ace744b4-0fad-42ce-b83f-3c38b225c433.png">

2021-11-17 13:02 UTC, mugnivenko commented
> breadcrumbs link is wrong, there's a console warning about it <img alt="Screenshot 2021-11-17 at 10 04 35" width="1440" src="https://user-images.githubusercontent.com/89010589/142179971-ace744b4-0fad-42ce-b83f-3c38b225c433.png">

it is because DynamicBreadcrumbs use localStorage. I fixed it, by rendering DynamicBreadcrumbs only on frontend

2021-11-17 13:48 UTC, merged