Fix/cc on review page
LBHackney-IT/lbh-adult-social-care-frontend pull request #363
Opened 2021-11-30 14:33 UTC by mugnivenko

https://app.clickup.com/t/1vqjfwc

2021-11-30 14:33 UTC, mugnivenko commented on components/Pages/CarePackages/BrokerCareCharge/ClaimsCollector.js
> -  const collectingReasonOptions = [
here i just delete this variable, and use constant instead

2021-11-30 14:35 UTC, mugnivenko commented on components/Pages/CarePackages/CareCharge/ProvisionalCareCharge.js
> +import { careChargeAPIKeys, careChargeFormKeys, COLLECTING_REASON_OPTIONS } from 'constants/variables';
rename constant to Upper case

2021-11-30 14:36 UTC, mugnivenko commented on components/Pages/CarePackages/ReviewPackageDetails/PackageInfo.js
> +                  {fncDetails.fncClaimCollector}
replace wrong variable name

2021-11-30 14:39 UTC, mugnivenko commented on components/Pages/ServiceUser/Packages/PackageRequest.js
> +      {!!packageRequest?.notes?.length && (
if length === 0 it show 0 in layout, i just convert it to boolean to fix issue

2021-12-01 09:05 UTC, mugnivenko commented
![image](https://user-images.githubusercontent.com/77606518/144204410-809588d7-3673-41c3-b61a-27c1d10b2569.png)
fix field to careCharges

2021-12-07 21:39 UTC, akeamwoodsND requested changes
better name for COLLECTING_REASON_OPTIONS

2021-12-08 08:34 UTC, mugnivenko commented
> better name for COLLECTING_REASON_OPTIONS

i changed name to CLAIM_REASON_OPTIONS. If this is wrong name, you can suggest your own version

2021-12-08 09:03 UTC, akeamwoodsND requested changes
merge latest, i need to test this with the latest work to double check something

2021-12-09 11:11 UTC, akeamwoodsND requested changes
url: /care-package/930ed6cb-8f45-4995-a061-b7b6dd87e7a0/details

Develop:
<img width="868" alt="Screenshot 2021-12-09 at 11 09 12" src="https://user-images.githubusercontent.com/89010589/145385751-a79c7e90-2e4f-4c50-a8fc-dd38b7251bb0.png">
your branch:
<img width="879" alt="Screenshot 2021-12-09 at 11 09 02" src="https://user-images.githubusercontent.com/89010589/145385762-1bf34102-996e-45cf-8a2b-874051e5846b.png">

why are you not showing cc information?  we should show this bit **if the care charge collector is supplier:**
<img width="386" alt="Screenshot 2021-12-09 at 11 10 13" src="https://user-images.githubusercontent.com/89010589/145385850-617ad8fb-7350-4957-ad70-380190f4ea32.png">
but not this bit:
<img width="376" alt="Screenshot 2021-12-09 at 11 10 48" src="https://user-images.githubusercontent.com/89010589/145385904-a84889b9-4325-48dc-89dd-103218fd2504.png">

**if collector is hackney** then we show it all like this:
<img width="465" alt="Screenshot 2021-12-09 at 11 11 15" src="https://user-images.githubusercontent.com/89010589/145385961-c2f698de-0038-411e-97e2-9891f79462b6.png">

2021-12-14 13:42 UTC, akeamwoodsND requested changes
view fnc link doesnt work
care-package/4bb38003-8872-4cd8-ad39-12987b227fca/review

<img width="832" alt="Screenshot 2021-12-14 at 13 41 24" src="https://user-images.githubusercontent.com/89010589/146009421-ca5236b2-eca4-44f5-8cbe-da874cb0c7f9.png">

2021-12-15 09:06 UTC, merged