Fix/care charges assessed
LBHackney-IT/lbh-adult-social-care-frontend pull request #380
Opened 2021-12-07 11:24 UTC by mugnivenko

https://app.clickup.com/t/1vrgpkb

2021-12-07 13:25 UTC, akeamwoodsND requested changes
blows up when:

- make new package
- add care charge with collect type 'supplier'
- ensure all dates on ongoing
notice how error appears

2021-12-07 16:15 UTC, akeamwoodsND requested changes

2021-12-08 08:21 UTC, mugnivenko commented on pages/care-package/[guid]/broker-care-charges.js
> +  } = careCharge;
it is useful for
![image](https://user-images.githubusercontent.com/77606518/145173485-f72441b3-d027-4e6b-a387-1ae39d7f7540.png)
and more

2021-12-09 10:53 UTC, akeamwoodsND commented on pages/care-package/[guid]/broker-care-charges.js
> +  } = careCharge;
that was all achieved before without destructuring.

2021-12-09 10:54 UTC, akeamwoodsND requested changes
you can actually use the 'reset' method from react-hook-form to remove all those 'setValues' we were doing
<img width="1198" alt="Screenshot 2021-12-09 at 10 53 02" src="https://user-images.githubusercontent.com/89010589/145383518-13e53aee-41f3-452f-ab50-a11e6d195fb5.png">

2021-12-14 13:37 UTC, akeamwoodsND requested changes

2021-12-14 13:37 UTC, akeamwoodsND commented on pages/care-package/[guid]/broker-care-charges.js
> +      isOngoing: endDate ? false : startDate,
isOngoing: !endDate

2021-12-20 12:46 UTC, akeamwoodsND requested changes
care-package/ce81a80a-8f2c-4581-acc9-633b4b036e4e/broker-care-charges 
(development) this has care charges but doesnt show announcement.

2021-12-20 14:02 UTC, akeamwoodsND requested changes
this package has care charges but announcement/banner isnt show
care-package/9e3e135c-93cd-46a1-b819-fa83f2f5caf3/broker-care-charges

2021-12-20 15:22 UTC, akeamwoodsND requested changes
<img width="1158" alt="Screenshot 2021-12-20 at 15 18 38" src="https://user-images.githubusercontent.com/89010589/146790324-b993fb1f-6d00-49f3-b78e-6cb09f98a54e.png">
should provide link to care charge instead like so (also change word 'done' to 'complete'):
<img width="713" alt="Screenshot 2021-12-20 at 15 21 39" src="https://user-images.githubusercontent.com/89010589/146790766-c486c740-9c53-4275-a935-37a709b3f428.png">

2021-12-20 15:24 UTC, merged