Feature/click document
LBHackney-IT/lbh-adult-social-care-frontend pull request #384
Opened 2021-12-08 08:17 UTC by mugnivenko

https://app.clickup.com/t/1nbqet2

2021-12-08 09:12 UTC, akeamwoodsND requested changes
<img width="507" alt="Screenshot 2021-12-08 at 09 11 48" src="https://user-images.githubusercontent.com/89010589/145181103-4389b77b-7323-48bd-b171-f74464389e09.png">

2021-12-08 09:21 UTC, mugnivenko commented on components/ViewDocument.js
> +      link=''
added link='' to fix boolean issue

2021-12-08 09:22 UTC, mugnivenko commented on components/ViewDocument.js
> +      link=''
also i removed useMemo, there is no reason for it

2021-12-09 10:51 UTC, akeamwoodsND requested changes
This should be a green download button
<img width="1299" alt="Screenshot 2021-12-09 at 10 50 16" src="https://user-images.githubusercontent.com/89010589/145382987-e0a3a9d4-9968-4662-a1ac-504f21b3ecdc.png">
then when you press it, it should download the file and then show a 'mark as paid button'... it doesn't show the mark as paid button unless you manually refresh the page

2021-12-09 10:51 UTC, akeamwoodsND requested changes
cannot see FNC file on review care package page even though i have uploaded one?

2021-12-09 13:18 UTC, mugnivenko commented
> cannot see FNC file on review care package page even though i have uploaded one?

yep, BE didn't send file info. Wait for Furkan fix it

2021-12-14 13:42 UTC, akeamwoodsND requested changes
merge issues

2021-12-15 10:34 UTC, akeamwoodsND requested changes
once you have downloaded the file, clicking the download button again should open the originally downloaded version rather than calling the endpoint again (e.g. cache/save the blob inside the component and reuse it rather than re-downloading it)

2021-12-16 09:26 UTC, akeamwoodsND requested changes
/payruns/ec2cfc82-4c2a-4ef7-aaf0-ddd01bbd555f

pressing download should not refresh page

2021-12-17 13:42 UTC, akeamwoodsND requested changes
get an error trying to upload file here: care-package/0612c38f-354d-4450-b59a-f3a8ed4412b7/core-package
<img width="576" alt="Screenshot 2021-12-17 at 13 40 37" src="https://user-images.githubusercontent.com/89010589/146553281-de829ac5-b8a7-4838-bfea-caa6e9a51d0e.png">
<img width="1440" alt="Screenshot 2021-12-17 at 13 41 06" src="https://user-images.githubusercontent.com/89010589/146553289-8a0ff868-60b7-4c12-a2d2-18eb847a9c2a.png">

2021-12-17 13:45 UTC, akeamwoodsND requested changes
file upload blows up on care charge page

<img width="1440" alt="Screenshot 2021-12-17 at 13 45 17" src="https://user-images.githubusercontent.com/89010589/146553672-2c97c650-51a2-434b-b772-7cd50c153724.png">

2021-12-17 13:48 UTC, akeamwoodsND requested changes
doesnt work /broker-referral/4/assign-package either
i don't think file upload works anywhere at the moment on this branch

2021-12-17 14:21 UTC, mugnivenko commented
1) I fixed getFormData function, there is no need to pass object. 

2) One more problem with uploading file using PUT request. I think it's BE side issue.

2021-12-20 13:04 UTC, akeamwoodsND requested changes
file upload gets this error on broker-referral/GUID/assign-package but **not on develop**
<img width="843" alt="Screenshot 2021-12-20 at 13 02 40" src="https://user-images.githubusercontent.com/89010589/146771423-924d4536-99b1-462c-a9ae-2f93799dfe8e.png">

2021-12-20 13:54 UTC, mugnivenko commented
> file upload gets this error on broker-referral/GUID/assign-package but **not on develop** <img alt="Screenshot 2021-12-20 at 13 02 40" width="843" src="https://user-images.githubusercontent.com/89010589/146771423-924d4536-99b1-462c-a9ae-2f93799dfe8e.png">

this is BE issue. Furkan working on it

2021-12-20 14:44 UTC, merged