added paidBy prop
LBHackney-IT/lbh-adult-social-care-frontend pull request #396
Opened 2021-12-10 11:34 UTC by mugnivenko

https://app.clickup.com/t/1x5b6e7

2021-12-12 13:18 UTC, akeamwoodsND requested changes

2021-12-12 13:18 UTC, akeamwoodsND commented on components/Pages/Payruns/HighLevelInsight/InsightButtons.js
>              12.01.2021
You haven't removed the hardcoded date...

2021-12-13 09:26 UTC, akeamwoodsND requested changes

2021-12-13 09:26 UTC, akeamwoodsND commented on components/Pages/Payruns/HighLevelInsight/InsightButtons.js
> +            {paidOn}
need to format date...

2021-12-13 09:29 UTC, mugnivenko commented on pages/payruns/[guid]/index.js
> +            paidOn={insightData?.paidOn && formatDate(insightData.paidOn)}
it already done

2021-12-13 11:42 UTC, merged